# Generated by Django 6.1 on 2026-09-10 19:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelTable(
            name="author",
            table="author",
        ),
        migrations.AlterModelTable(
            name="book",
            table="book",
        ),
    ]
